# Generated by Django 4.2.4 on 2023-08-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75, unique=True)),
                ('plataforma', models.CharField(max_length=75)),
                ('empresa_desenvolvedora', models.CharField(max_length=50)),
                ('ano_lancamento', models.DateField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
