# Generated by Django 4.2.4 on 2023-08-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='ano_lancamento',
            field=models.IntegerField(),
        ),
    ]
