# Generated by Django 4.2.4 on 2023-08-23 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=60)),
                ('discord', models.CharField(default='Não possui', max_length=100)),
                ('disponivel_para_torneio', models.BooleanField(default=False)),
                ('foto_de_perfil', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioJoga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_perfil_jogador', models.CharField(blank=True, max_length=150)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.jogos')),
            ],
        ),
    ]
