# Generated by Django 4.2.4 on 2023-09-27 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NickUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('discord', models.CharField(default='Não possui', max_length=100)),
                ('disponivel_para_torneio', models.BooleanField(default=False)),
                ('regiao_server', models.CharField(blank=True, default='Único', max_length=75)),
                ('foto_de_perfil', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioJoga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_perfil_jogador', models.CharField(blank=True, max_length=150)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogo', to='jogos.jogos')),
                ('nick_jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nickname', to='usuarios.nickusuario')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plataforma_usada', to='jogos.plataforma')),
            ],
        ),
        migrations.AddField(
            model_name='nickusuario',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nicknames', to='usuarios.usuario'),
        ),
    ]
