# Generated by Django 4.2.4 on 2023-09-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='regiao_server',
        ),
        migrations.AddField(
            model_name='nickusuario',
            name='regiao_server',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
