# Generated by Django 4.2.4 on 2023-08-30 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0003_usuario_id_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_auth_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rel_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
