# Generated by Django 4.2.4 on 2023-09-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_id_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_auth_user',
        ),
    ]
